services:
  - type: web
    name: needledrop-ml-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python api_classificacao.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
